# Generated by Django 5.0.14 on 2026-02-28 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.media'),
        ),
        migrations.AddField(
            model_name='historytimelineevent',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.media'),
        ),
        migrations.AddField(
            model_name='notablefigure',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.media'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.media'),
        ),
        migrations.AddField(
            model_name='notablefigure',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notable_figures', to='archive.villagehistory'),
        ),
        migrations.AddField(
            model_name='historytimelineevent',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='archive.villagehistory'),
        ),
        migrations.AddField(
            model_name='youthblogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='youthblogpost',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.media'),
        ),
    ]
