# Generated by Django 4.2.28 on 2026-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historytimelineevent',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historytimelineevent',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notablefigure',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notablefigure',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='caption_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagehistory',
            name='founding_story_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthblogpost',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthblogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
