# Generated by Django 5.0.14 on 2026-02-28 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_phone', models.CharField(max_length=30)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_requests', to='crops.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_requests', to='farmers.farmer')),
            ],
            options={
                'db_table': 'order_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
