# Generated by Django 4.2.28 on 2026-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='preferred_contact_time_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
