# Generated by Django 5.0.14 on 2026-02-28 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('onion', 'Onion'), ('sesame', 'Sesame'), ('rice', 'Rice'), ('bean', 'Bean'), ('corn', 'Corn'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('herb', 'Herb'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity_available', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='crops', to='farmers.farmer')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.media')),
            ],
            options={
                'db_table': 'crops',
            },
        ),
        migrations.CreateModel(
            name='CropHarvestMonth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_months', to='crops.crop')),
            ],
            options={
                'db_table': 'crop_harvest_months',
                'unique_together': {('crop', 'month')},
            },
        ),
    ]
