# Generated by Django 4.2.28 on 2026-03-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
