# Generated by Django 4.2.28 on 2026-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='crop_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='market_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='unit_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
