# Generated by Django 4.2.28 on 2026-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_hub', '0002_announcement_body_en_announcement_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
